### ISSUE TITLE
Pressing "Go!" yields error "An error has occurred. Check your logs or contact the app author for clarification."

### ISSUE THREAD

**Issue by RitschDS** [tyluRp/catfacts#3]
On a brisk Winter's day, I found myself in a mood for some catfacts. I recalled to myself that a good friend from days before created a electronic interface to serve up such things. So I went to https://tylerlittlefield.com/shiny/tyler/catfacts/

BUT lo, upon pressing that button of which feline facts are to erupt... an error message was generated!

"An error has occurred. Check your logs or contact the app author for clarification."

OH THE HUMANITY!

**Comment by tylerlittlefield** [comment]
thanks............ fixed :D
